In [2]:
import os
import pandas as pd

In [5]:
directory = "../data/implicit-hate-corpus"
tsv_files = [f for f in os.listdir(directory) if ".tsv" in f]
dfs = {}
for tsv in tsv_files:
    filepath = os.path.join(directory, tsv)
    df = pd.read_csv(filepath, sep="\t")
    dfs[tsv] = df

In [6]:
dfs.keys()

dict_keys(['implicit_hate_v1_SAP_posts.tsv', 'implicit_hate_v1_stg1.tsv', 'implicit_hate_v1_stg1_posts.tsv', 'implicit_hate_v1_stg2.tsv', 'implicit_hate_v1_stg2_posts.tsv', 'implicit_hate_v1_stg3.tsv', 'implicit_hate_v1_stg3_posts.tsv'])

In [9]:
for filename, df in dfs.items():
    print(filename, df.shape)
    print(df.columns)
    print()

implicit_hate_v1_SAP_posts.tsv (548, 2)
Index(['ID', 'post'], dtype='object')

implicit_hate_v1_stg1.tsv (21480, 2)
Index(['ID', 'class'], dtype='object')

implicit_hate_v1_stg1_posts.tsv (21480, 2)
Index(['post', 'class'], dtype='object')

implicit_hate_v1_stg2.tsv (6346, 3)
Index(['ID', 'implicit_class', 'extra_implicit_class'], dtype='object')

implicit_hate_v1_stg2_posts.tsv (6346, 3)
Index(['post', 'implicit_class', 'extra_implicit_class'], dtype='object')

implicit_hate_v1_stg3.tsv (6359, 3)
Index(['ID', 'target', 'implied_statement'], dtype='object')

implicit_hate_v1_stg3_posts.tsv (6359, 3)
Index(['post', 'target', 'implied_statement'], dtype='object')

In [10]:
dfs['implicit_hate_v1_SAP_posts.tsv']

            ID                                               post
0    SAP_10011  Guys I have a question: when a gay couple gets...
1    SAP_10036  Heard this from a 12 year old: 'Whats the diff...
2    SAP_10045  Friend: how dark is your humor? Me: If you whi...
3    SAP_10051  What do you say to a black guy in a three piec...
4    SAP_10085  how do you call a black man you call his cell ...
..         ...                                                ...
543   SAP_9953  How do you get a black man out of a tree? Cut ...
544   SAP_9960  Helen Keller walked into a bar and then a chai...
545   SAP_9962  Why do sumo wrestlers shave their legs? So tha...
546   SAP_9966  What's the difference between a black slave an...
547   SAP_9989  Why did Beyonce say "to the left,to the left"?...

[548 rows x 2 columns]

In [11]:
dfs['implicit_hate_v1_stg1.tsv']

                       ID          class
0      399886440588247041  implicit_hate
1      929901925100937216       not_hate
2      728678509497954304       not_hate
3      625688620444180481       not_hate
4      441089979322597376       not_hate
...                   ...            ...
21475           SAP_17154  implicit_hate
21476           SAP_17179  implicit_hate
21477           SAP_17314  implicit_hate
21478           SAP_17343  implicit_hate
21479           SAP_17406  implicit_hate

[21480 rows x 2 columns]

In [12]:
dfs['implicit_hate_v1_stg1_posts.tsv']

                                                    post          class
0        " : jewish harvard professor noel ignatiev w...  implicit_hate
1       b.higher education is a part of european cult...       not_hate
2       has a problem with  " the whites " " and " " ...       not_hate
3       is yasir qadhi a hate preacher for calling ch...       not_hate
4       rt  " : how three million germans mass murder...       not_hate
...                                                  ...            ...
21475  Seeing prostitutes is morally wrong, but being...  implicit_hate
21476  I wonder how many females I raped today I spen...  implicit_hate
21477  Having a criminal record is more attractive to...  implicit_hate
21478  Another advantage of being a female: getting b...  implicit_hate
21479  If men are so privileged and women have it so ...  implicit_hate

[21480 rows x 2 columns]

In [16]:
dfs['implicit_hate_v1_stg1_posts.tsv']['class'].value_counts()

class
not_hate         13291
implicit_hate     7100
explicit_hate     1089
Name: count, dtype: int64

In [13]:
dfs['implicit_hate_v1_stg2.tsv']

                      ID   implicit_class extra_implicit_class
0     399886440588247041  white_grievance                  NaN
1     755109998770921473            irony                  NaN
2     251422864232808449  white_grievance                  NaN
3     548214253497249792    stereotypical                  NaN
4     184109665108504579    stereotypical                  NaN
...                  ...              ...                  ...
6341           SAP_17154            irony                  NaN
6342           SAP_17179            irony                  NaN
6343           SAP_17314    stereotypical                  NaN
6344           SAP_17343      inferiority                  NaN
6345           SAP_17406            irony                  NaN

[6346 rows x 3 columns]

In [14]:
dfs['implicit_hate_v1_stg3.tsv']

,ID,target,implied_statement
0,524408721473306625,minority groups,people in minority groups are all in gangs
1,394530795580174337,non-white people,non-white people are dangerous
2,794539075164401666,Immigrants,Immigrants are undesirable
3,901162469992808448,Anti-whites,Anti-whites hate white people
4,911282139706007553,Capitalists,Capitalists don't like white people.
...,...,...,...
6354,884073715490861056,Asian folks,Asian folks have destroyed the country
6355,603471575833137153,Immigrants,Immigrants are sexual offenders
6356,669074062862368768,Indian folks,Indian folks are pigs
6357,466220911675179008,Indian folks,Indian folks are uneducated
6358,481873407898693632,Indian folks,Indian folks are facist

In [15]:
dfs['implicit_hate_v1_stg3_posts.tsv']

,post,target,implied_statement
0,"rt "" white privilege "" "" is when the gun jam...",minority groups,people in minority groups are all in gangs
1,if you are white in that state watch yourself !,non-white people,non-white people are dangerous
2,so the 500 % increase in h1b visas ? yeah i'm ...,Immigrants,Immigrants are undesirable
3,rt antiwhites expose their hatred of white ki...,Anti-whites,Anti-whites hate white people
4,capitalism like communism is an enemy of the...,Capitalists,Capitalists don't like white people.
...,...,...,...
6354,your people came to a friendly and highly popu...,Asian folks,Asian folks have destroyed the country
6355,it's as if sexual abuse follows perkins around .,Immigrants,Immigrants are sexual offenders
6356,every india lover must boycott these pigs movies,Indian folks,Indian folks are pigs
6357,ask more rss intellectuals to come on powerful...,Indian folks,Indian folks are uneducated
6358,cong stooges in msm who underplay the darkest ...,Indian folks,Indian folks are facist